### ISSUE TITLE
zip files that cause grader exceptions

### ISSUE THREAD

**Issue by bill-auger** [saasbook/hw-bdd-cucumber#8]
lord-jabronious's file causes "There was a fatal error with your submission. It either timed out or caused an exception."

**Comment by lord-jabronious** [comment]
[features.zip](https://github.com/saasbook/hw-bdd-cucumber/files/357877/features.zip)

**Comment by bill-auger** [comment]
lord-jabronious's file has the following structure

```
$ tree features
features
├── filter_movie_list.feature
├── sort_movie_list.feature
├── step_definitions
│   ├── movie_steps.rb
│   └── web_steps.rb
└── support
    ├── env.rb
    ├── paths.rb
    └── selectors.rb


$ ls -al features/*
-rw-r--r-- 1 ubuntu ubuntu 1972 Jul 11 19:19 features/filter_movie_list.feature
-rw-r--r-- 1 ubuntu ubuntu 1183 Jul 11 02:45 features/sort_movie_list.feature

features/step_definitions:
total 20
drwxr-xr-x 2 ubuntu ubuntu 4096 Jul 10 02:13 ./
drwxr-xr-x 4 ubuntu ubuntu 4096 Jul 10 02:13 ../
-rw-r--r-- 1 ubuntu ubuntu 2012 Jul 11 19:15 movie_steps.rb
-rw-r--r-- 1 ubuntu ubuntu 7128 Jul 10 02:13 web_steps.rb

features/support:
total 20
drwxr-xr-x 2 ubuntu ubuntu 4096 Jul 10 02:13 ./
drwxr-xr-x 4 ubuntu ubuntu 4096 Jul 10 02:13 ../
-rw-r--r-- 1 ubuntu ubuntu 2623 Jul 11 19:05 env.rb
-rw-r--r-- 1 ubuntu ubuntu 1396 Jul 11 19:03 paths.rb
-rw-r--r-- 1 ubuntu ubuntu 1061 Jul 10 02:13 selectors.rb


$ file features/*
features/filter_movie_list.feature: Python script, ASCII text executable
features/sort_movie_list.feature:   ASCII text
features/step_definitions:          directory 
features/support:                   directory

$ file features/step_definitions/*
features/step_definitions/movie_steps.rb: ASCII text
features/step_definitions/web_steps.rb:   Ruby script, ASCII text

$ file features/support/*
features/support/env.rb:       Ruby script, ASCII text
features/support/paths.rb:     Ruby module source, ASCII text
features/support/selectors.rb: Ruby module source, ASCII text
```

**Comment by tansaku** [comment]
thanks @bill-auger I'll take a look at this

**Comment by tansaku** [comment]
this get's totally stuck for me on submission - not even a "fatal error with your submission"

**Comment by tansaku** [comment]
@bill-auger - I'm running this against my local grader and getting the following error:

```sh
     unknown attribute 'released_date' for Movie. (ActiveRecord::UnknownAttributeError)
      ./submissions/506af89a6181960fc69f47f1fbc8d708/assignment3/2016-07-14-11-57-27/features/step_definitions/movie_steps.rb:7:in `block (2 levels) in <top (required)>'
      ./submissions/506af89a6181960fc69f47f1fbc8d708/assignment3/2016-07-14-11-57-27/features/step_definitions/movie_steps.rb:4:in `each'
      ./submissions/506af89a6181960fc69f47f1fbc8d708/assignment3/2016-07-14-11-57-27/features/step_definitions/movie_steps.rb:4:in `/the following movies exist/'
      submissions/506af89a6181960fc69f47f1fbc8d708/assignment3/2016-07-14-11-57-27/features/filter_movie_list.feature:9:in `Given the following movies exist:'
```

has the student run this on their local machine?  looks like it wouldn't pass there ...

**Comment by tansaku** [comment]
of course what we'd really like is the grader to actually share that output with the student!!!
